#!/bin/bash
start () {
iptables-restore < /etc/iptables/rules.v4
ip6tables-restore < /etc/iptables/rules.v6}

stop () {
iptables-save > /etc/iptables/rules.v4
ip6tables-save > /etc/iptables/rules.v6}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
esac
exit 0
